### ISSUE TITLE
getting empty space using data-ag-x

### ISSUE THREAD

**Issue by proscriptsell** [kamalkhan/awesome-grid#3]
Hi
Thanks for share a great js scripts . i really like this ,  i am facing  some  problem when using data-ag-x , You can check each row last item or you can check screenshot attah
![empty-space](https://cloud.githubusercontent.com/assets/7761441/19893360/18a0c30a-a073-11e6-84ae-1145405b7558.png)

Thanks

**Comment by kamalkhan** [comment]
Kindly replicate the bug in http://jsbin.com so that I may tinker around it.

**Comment by proscriptsell** [comment]
HI
Thanks for your quicly reply : please check there http://jsbin.com/pexupu/edit?html,css,js,output 

Thanks

**Comment by kamalkhan** [comment]
Okay, thats normal behaviour in this situation because when 04 is added to the grid, it takes the rest of the space. The next box can not be placed in the empty slot because it will break the layout below it. By looking at it you may visualize that the next box can fit into it, but thats just an exception, consider a box that is much larger in height?

Hence, this isn't a bug. If you stilll need to tune it, you may change the order of the divs/boxes.
